apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: nattapatsiripin-com-tls
spec:
  secretName: nattapatsiripin-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: nattapatsiripin.com
  dnsNames:
    - nattapatsiripin.com
    - www.nattapatsiripin.com
